import { ReduxProvider } from '@/redux/provider'
import type { Metadata } from 'next'
import { Roboto_Flex as Roboto, } from 'next/font/google'
import './globals.css'

const roboto = Roboto({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body className={roboto.className}>{children}</body>
      </ReduxProvider>
    </html>
  )
}
